version: "3"

service:
  jenkins:
    image: "jenkins/jenkins:lts"
    volumes:
      - jenkins_volume:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8090:8080"
      - "50000:50000"
    user: root
